# Generated by Django 3.1.4 on 2021-07-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionStudyRegister', '0002_studyregister_approved_by_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyregister',
            name='declined_by_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
