# Generated by Django 3.1.4 on 2021-07-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionStudyRegister', '0003_studyregister_declined_by_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyregister',
            name='actioned_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
