# Generated by Django 3.1.4 on 2021-07-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionComplaintBox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='raised_by',
            field=models.CharField(max_length=255),
        ),
    ]
