# Generated by Django 3.1.4 on 2021-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionComplaintBox', '0002_auto_20210709_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
