# Generated by Django 3.1.4 on 2021-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_phone_number', models.IntegerField(null=True)),
                ('student_class', models.IntegerField(null=True)),
                ('date_of_joining', models.DateTimeField()),
                ('fees', models.IntegerField(null=True)),
            ],
        ),
    ]
