# Generated by Django 3.1.4 on 2021-07-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
