# Generated by Django 3.1.4 on 2021-07-11 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TuitionDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2Complaint_access',
            fields=[
                ('a2c_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('a2c_access', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('description', models.CharField(default='bg-danger', max_length=200)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_phone_number', models.IntegerField(null=True)),
                ('student_class', models.IntegerField(null=True)),
                ('date_of_joining', models.DateTimeField()),
                ('fees', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='A2Presence_access',
            fields=[
                ('a2p_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('a2p_access', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('description', models.CharField(default='bg-success', max_length=200)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('leader_id', models.AutoField(primary_key=True, serialize=False)),
                ('leader_roles', models.CharField(choices=[('Admininstrator', 'Admininstrator'), ('Check-in Leader', 'Check-in Leader'), ('File Leader', 'File Leader'), ('Diary Leader', 'Diary Leader')], max_length=200)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('leader_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_phone_number', models.IntegerField(null=True)),
                ('student_class', models.IntegerField(null=True)),
                ('date_of_joining', models.DateTimeField()),
                ('fees', models.IntegerField(null=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
