# Generated by Django 3.1.4 on 2021-07-09 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TuitionDB', '0002_auto_20210708_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('leader_id', models.AutoField(primary_key=True, serialize=False)),
                ('leader_roles', models.CharField(choices=[('Check-in Leader', 'Check-in Leader'), ('File Leader', 'File Leader'), ('Diary Leader', 'Diary Leader')], max_length=200)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('leader_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='A2Portal_access',
            fields=[
                ('a2p_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('a2p_access', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
