# Generated by Django 3.1.4 on 2021-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionDB', '0003_auto_20210711_1607'),
    ]

