# Generated by Django 3.1.4 on 2021-07-10 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TuitionDB', '0003_a2portal_access_leader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A2Portal_access',
            new_name='A2Complaint_access',
        ),
        migrations.RenameField(
            model_name='a2complaint_access',
            old_name='a2p_access',
            new_name='a2c_access',
        ),
        migrations.RenameField(
            model_name='a2complaint_access',
            old_name='a2p_access_id',
            new_name='a2c_access_id',
        ),
        migrations.CreateModel(
            name='A2Presence_access',
            fields=[
                ('a2p_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('a2p_access', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
