# Generated by Django 3.1.4 on 2021-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionDB', '0003_auto_20210711_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Portal',
            fields=[
                ('portal_id', models.AutoField(primary_key=True, serialize=False)),
                ('portal_name', models.CharField(max_length=200)),
                ('portal_desc', models.CharField(max_length=200)),
                ('description', models.CharField(default='bg-success', max_length=200)),
                ('portal_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
