# Generated by Django 3.1.4 on 2021-07-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionDB', '0005_auto_20210711_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Portal',
        ),
    ]
