# Generated by Django 3.1.4 on 2021-07-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_phone_number',
            field=models.CharField(blank=True, default='0', max_length=500),
        ),
    ]
