# Generated by Django 3.1.4 on 2021-07-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionDB', '0009_auto_20210713_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cbse_metric',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_person',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
