# Generated by Django 3.1.4 on 2021-07-16 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TuitionDB', '0010_auto_20210713_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='leader_roles',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Teacher', 'Teacher'), ('Check-in Leader', 'Check-in Leader'), ('File Leader', 'File Leader'), ('Diary Leader', 'Diary Leader')], max_length=200),
        ),
        migrations.CreateModel(
            name='A2Study_access',
            fields=[
                ('a2s_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('a2s_access', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('description', models.CharField(default='bg-danger', max_length=200)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
