# Generated by Django 3.1.4 on 2021-07-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionAttendance', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in_out_register',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
    ]
