# Generated by Django 3.1.4 on 2021-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionAttendance', '0002_auto_20210708_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_in_out_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True)),
                ('attendance_date', models.DateField()),
                ('half_day', models.BooleanField(default=False)),
                ('in_time', models.DateTimeField(auto_now=True)),
                ('out_time', models.DateTimeField(default=None)),
                ('status', models.CharField(default='Not Arrived', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
