# Generated by Django 3.1.4 on 2021-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionAttendance', '0003_auto_20210708_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in_out_register',
            name='attendance_date',
            field=models.DateField(auto_now=True),
        ),
    ]
