# Generated by Django 3.1.4 on 2021-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionAttendance', '0004_auto_20210708_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_in_out_register',
            name='id',
        ),
        migrations.AddField(
            model_name='check_in_out_register',
            name='entry_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
