# Generated by Django 3.1.4 on 2021-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionAttendance', '0006_auto_20210708_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in_out_register',
            name='out_time',
            field=models.DateTimeField(),
        ),
    ]
