# Generated by Django 3.1.4 on 2021-10-24 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastExaminationScoreOut',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=200)),
                ('max_mark', models.IntegerField(null=True)),
                ('english_mark', models.IntegerField(default=0)),
                ('is_english', models.BooleanField(default=True)),
                ('tamil_mark', models.IntegerField(default=0)),
                ('is_tamil', models.BooleanField(default=True)),
                ('science_mark', models.IntegerField(default=0)),
                ('is_science', models.BooleanField(default=True)),
                ('social_mark', models.IntegerField(default=0)),
                ('is_social', models.BooleanField(default=True)),
                ('maths_mark', models.IntegerField(default=0)),
                ('is_maths', models.BooleanField(default=True)),
                ('computer_mark', models.IntegerField(default=0)),
                ('is_computer', models.BooleanField(default=True)),
                ('total_mark', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
