# Generated by Django 3.1.4 on 2021-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionExamination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexaminationscoreout',
            name='show_ld',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
