# Generated by Django 3.1.4 on 2021-10-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionExamination', '0002_lastexaminationscoreout_show_ld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastexaminationscoreout',
            name='total_mark',
            field=models.IntegerField(default=0),
        ),
    ]
