# Generated by Django 3.1.4 on 2021-10-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionExamination', '0003_auto_20211025_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastexaminationscoreout',
            name='show_ld',
            field=models.DateTimeField(),
        ),
    ]
