# Generated by Django 4.0 on 2022-01-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeesCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('paid_year', models.IntegerField()),
                ('late_pay', models.BooleanField(default=False)),
                ('late_pay_fine', models.IntegerField(default=0)),
                ('payment_on', models.DateTimeField(auto_now=True)),
                ('paid_for', models.CharField(max_length=200)),
                ('paid_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TuitionFees.month')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
