# Generated by Django 4.0 on 2022-01-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionFees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feescollector',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('CARD', 'CARD')], default='CASH', max_length=200),
        ),
    ]
