# Generated by Django 4.0 on 2022-01-07 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerClass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerclassregistration',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 19, 57, 5, 868094)),
        ),
    ]
