# Generated by Django 4.0 on 2022-01-08 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerClass', '0003_alter_computerclassregistration_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerclassregistration',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 9, 0, 17, 25, 251749)),
        ),
    ]
