# Generated by Django 4.0.2 on 2022-03-28 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerClass', '0005_alter_computerclassregistration_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerclassregistration',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 28, 23, 30, 49, 860261)),
        ),
    ]
